server:
  port: 8082

spring:
  application:
    name: microservicio-facturacion
  datasource:
    url: jdbc:mysql://mysql-facturacion-svc:3306/facturacion_db
    username: admin
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  rabbitmq:
    host: rabbitmq-svc
    port: 5672
    username: admin
    password: admin123

# URLs de otros servicios
services:
  central:
    url: http://central-svc:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.agroflow: DEBUG