server:
  port: 8080

spring:
  application:
    name: SERVICE-CENTRAL
  datasource:
    url: jdbc:postgresql://postgres-svc:5432/agroflow_central
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: rabbitmq-svc
    port: 5672
    username: admin
    password: admin123

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.agroflow: INFO
    org.springframework.amqp: WARN