apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventario
  namespace: agroflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventario
  template:
    metadata:
      labels:
        app: inventario
    spec:
      containers:
        - name: inventario
          image: franciscoteran2001/agroflow-inventario:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "kubernetes"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-inventario-svc:3306/inventario_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agroflow-secrets
                  key: mysql-password
            - name: SPRING_RABBITMQ_HOST
              value: "rabbitmq-svc"
            - name: SPRING_RABBITMQ_USERNAME
              value: "admin"
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agroflow-secrets
                  key: rabbitmq-password
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 768Mi