apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-facturacion
  namespace: agroflow-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-facturacion
  template:
    metadata:
      labels:
        app: mysql-facturacion
    spec:
      containers:
        - name: mysql
          image: mysql:8
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root123"
            - name: MYSQL_DATABASE
              value: "facturacion_db"
            - name: MYSQL_USER
              value: "admin"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agroflow-secrets
                  key: mysql-password
          args:
            - --default-authentication-plugin=mysql_native_password
          resources:
            requests:
              cpu: 100m      # ⬇️ Reducido de 200m
              memory: 256Mi  # ⬇️ Reducido de 512Mi
            limits:
              cpu: 300m      # ⬇️ Reducido de 500m
              memory: 512Mi  # ⬇️ Reducido de 1Gi
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          emptyDir: {}