apiVersion: v1
kind: Service
metadata:
  name: mysql-inventario-svc
  namespace: agroflow-ns
spec:
  selector:
    app: mysql-inventario
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP